### ISSUE TITLE
Wrong JSON.parse on request to Twitch

### ISSUE THREAD

**Issue by pioupia** [Plazide/node-twitch#25]
Hello, 
My client sent me an error that came from your package. I searched your code a little to find out where it came from, but to no avail. I think it was corrected, but unfortunately the module is up to date on our side.
It indicates a problem parsing information retrieved from Twitch. 
I thinks, the request is for get the channel of user and no the login to Twitch.
`/helix/streams?user_login=<user_name of user>&&channel=<the same username>`

**Comment by Plazide** [comment]
Hey, thanks for reporting.

I cannot reproduce. Could you provide the error message and the parameters example of parameters that cause this issue? 

I'm a bit confused as to what you are saying, but if you mean that the issue has disappeared, it might have been a temporary error with the Twitch API. I don't know, though.

**Comment by pioupia** [comment]
Yeah ! I'm sorry for the wait.
![screenshot](https://cdn.discordapp.com/attachments/794480379796520971/859730046074748928/unknown.png)

**Comment by Plazide** [comment]
Okay, that's strange.

There are two errors with the query.
1. There should not be two ampersands (&)
2. Channel is not a valid option for the streams endpoint

It seems like there is something wrong with your options for the `getStreams` method.

Check your code where you are calling `twitch.getStreams`, it should look like this:
```js
twitch.getStreams({ channel: "ultrasaucisse" })
```

**Comment by pioupia** [comment]
I've this code :
```js
const stream = await twitch.getStreams({
    channel: stmr[0]
});
```

stmr[0] is the channel name. It's strange because I don't have any errors, and my client have a VPS and he get this error. I don't know why but... It's juste strange.
Thanks you anyway.

**Comment by Plazide** [comment]
Okay, so that query is actually normal, but still a bug. I just checked the output of the query when running the tests (which are passing), and it looks exactly like the one you in your request. That means the error is not with the query.

The error indicates that the result was an HTML file (based on the `<`). Twitch should never return HTML files, they always return JSON. Based on that, it's either a temporary Twitch error or an incorrectly configured VPS (ie. not allowing outbound calls).

It doesn't seem to be an error with the package, but let me know if you find something that suggests otherwise.

**Comment by pioupia** [comment]
I think you’re right. I’m not sure if it’s possible with node-fetch if you use this package because I’ve never looked too hard. But why not get the html code with a `res.text()` and then do a typeof of the response to see if it is an object or not. That could rule out that kind of mistake.
But thank you for the verification, it’s very likely.
